# Generated by Django 4.2.4 on 2023-08-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouraria.fornecedor')),
                ('tipo_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouraria.tipo_conta')),
            ],
        ),
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagadaor', models.CharField(max_length=75)),
                ('data_recebimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade')),
                ('tipo_arrecadacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesouraria.tipo_arrecadacao')),
            ],
        ),
    ]
