# Generated by Django 4.2.4 on 2023-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_arrecadacao',
            name='nome',
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_conta',
            name='nome',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
