# Generated by Django 4.2.4 on 2023-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0004_contas_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrecadacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
