# Generated by Django 4.2.4 on 2023-09-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0005_arrecadacao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrecadacao',
            old_name='pagadaor',
            new_name='pagador',
        ),
    ]
