# Generated by Django 4.2.4 on 2023-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0006_rename_pagadaor_arrecadacao_pagador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
