# Generated by Django 4.2.7 on 2023-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0009_alter_arrecadacao_entidade_alter_contas_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='comprovante',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
