# Generated by Django 4.2.7 on 2023-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0010_contas_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
