# Generated by Django 4.2.4 on 2023-08-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=75)),
                ('celular', models.CharField(max_length=15)),
                ('marcon', models.BooleanField(default=False)),
                ('demolay', models.BooleanField(default=False)),
                ('escudeiro', models.BooleanField(default=False)),
                ('abelhinha', models.BooleanField(default=False)),
                ('fdj', models.BooleanField(default=False)),
                ('rosa_do_oriente', models.BooleanField(default=False)),
                ('clube_da_fraternidade', models.BooleanField(default=False)),
                ('parentesco_maconico', models.CharField(choices=[('FILHO(A)', 'Filho(a)'), ('ESPOSA', 'Esposa'), ('SOBRINHO(A)', 'Sobrinho(a)'), ('NETO(A)', 'Neto(a)'), ('SEM_PARENTESCO', 'Sem Parentesco')], default='SEM PARENTESCO', max_length=20)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade')),
            ],
        ),
    ]
