# Generated by Django 4.2.4 on 2023-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0002_alter_membro_parentesco_maconico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='nome',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
