# Generated by Django 4.2.4 on 2023-08-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0003_alter_patrimonio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
