# Generated by Django 4.2.4 on 2023-09-04 16:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0004_membro_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
