# Generated by Django 4.2.7 on 2023-12-18 20:51

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entidade', '0007_membro_user_patrimonio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='abelhinha',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='clube_da_fraternidade',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='demolay',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='entidade',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='escudeiro',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='fdj',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='marcon',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='parentesco_maconico',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='rosa_do_oriente',
        ),
        migrations.AddField(
            model_name='membro',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14, verbose_name='cpf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membro',
            name='endereco',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.CreateModel(
            name='Percapta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
                ('captacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmsb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cmi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fdj_gleb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dm_gleb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dm_atalaia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fdj_atalia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovante', models.ImageField(blank=True, upload_to='')),
                ('percapita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.percapta')),
            ],
        ),
    ]
