# Generated by Django 4.2.7 on 2023-12-19 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entidade', '0008_remove_membro_abelhinha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='membro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entidade.membro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
